### ISSUE TITLE
Language contamination

### ISSUE THREAD

**Issue by paulcanning** [petrovicstefanrs/30_seconds_of_knowledge#1]
See here:

https://github.com/30-seconds/30-seconds-of-code/issues/917#issuecomment-461469797

**Comment by petrovicstefanrs** [comment]
Hey @paulcanning , this has been already brought to my attention. It is a bug I'm working on resolving. As soon as it's resolved I'll close this issue so you will be informed.

**Comment by petrovicstefanrs** [comment]
Fixed in commit cf119c0f0eb7ac59eb45ad6c990861dc6e6cb9c4
