### ISSUE TITLE
support for 30-Seconds-of-C++

### ISSUE THREAD

**Issue by Bhupesh-V** [petrovicstefanrs/30_seconds_of_knowledge#10]
Any chances the extension could provide Code Snippets from [30-Seconds-Of-STL](https://github.com/Bhupesh-V/30-Seconds-Of-STL) .

**Comment by petrovicstefanrs** [comment]
@Bhupesh-V Hey man, I mean sure. Give me a day or two, to write the documentation for contributions regarding new snippets and snippet libraries, and you can branch-out and start adding the snippets.

Just a small info, would this be called the c++ library or stl library in the interface. I want to keep the extension "self-explanatory" to new comers and experienced developers as well. C++ would be ideal name but I assume you gave your repo STL name for a good reason (Standard Template Library). Now I'm not familiar with c++ to much so your input on this would be great.

**Comment by Bhupesh-V** [comment]
@petrovicstefanrs :+1: 
I guess naming it `C++` (in your extension) would be a good idea because people don't easily recognise STL
(Well there was NO specific reason to name it `30-Seconds-Of-STL`)
Just ping me when you are done adding CONTRIBUTING guidelines I will make changes in my project accordingly :smiley:

**Comment by petrovicstefanrs** [comment]
@Bhupesh-V Great, I'll do the documentation in the next day or two and ping you here once I do so you don't have to be on the lookout for it.

**Comment by Bhupesh-V** [comment]
Hey @petrovicstefanrs any updates ??

**Comment by petrovicstefanrs** [comment]
@Bhupesh-V Sorry took me longer that expected, life got in the way. I've finished the documentation for all the currently present snippets. If you want you can start implementing the c++ snippets based on how the current ones are implemented. Just make sure to branch out of dev branch and name your branch feature/cpp_snippets

**Comment by Bhupesh-V** [comment]
Ok i have renamed the project to **30-seconds-of-cpp**
So now what how would this be integrated with the extension ??
