### ISSUE TITLE
New Langage Library: Kotlin

### ISSUE THREAD

**Issue by farkerhaiku** [petrovicstefanrs/30_seconds_of_knowledge#17]
I saw there's an unofficial 30 seconds of kotlin, and since I'm an android dev I'd like to see that added to this super cool extension.  

https://github.com/IvanMwiruki/30-seconds-of-kotlin

I'm not sure how hard it will be to include something like that in this plugin, but if you can point me to a where I can learn how to contribute new snippets I'd be happy to give it a whirl

**Comment by petrovicstefanrs** [comment]
Hey @farkerhaiku , 
The contributor documentation should be finished soon enough so if you choose to help out it would be great. Until then I'll look into the repo you provided to see if there are any issues on using their snippets inside the extension.
