### ISSUE TITLE
Doesn't display after browser restart

### ISSUE THREAD

**Issue by akronborn** [petrovicstefanrs/30_seconds_of_knowledge#18]
The icon is still visible in the toolbar. The options to show in incognito mode are selected, however, the extension does not come up when I open a new tab. It does continue to work outside of incognito mode.

**Comment by petrovicstefanrs** [comment]
I wasn't aware that someone would want to use the extension in incognito mode. I will have to look into it to see if the new tab extensions are supported in incognito

**Comment by qiandongyq** [comment]
@akronborn @petrovicstefanrs Incognito windows are treated specially. New Tab pages cannot be overridden in incognito windows.

source: https://developer.chrome.com/extensions/override

**Comment by petrovicstefanrs** [comment]
@qiandongyq Thanks for the info. I'll close this issue then as it seams nothing can be done for incognito.
