### ISSUE TITLE
Links to other tips not loading

### ISSUE THREAD

**Issue by sanderlenaerts** [petrovicstefanrs/30_seconds_of_knowledge#23]
![image](https://user-images.githubusercontent.com/7161447/53693991-47ce1900-3da8-11e9-96cc-95e84b6154f7.png)

The _off_ link adds #off to the url, but it does not load the actual tip

**Comment by asantarissy** [comment]
Thanks @sanderlenaerts yes that's correct, but 30 Seconds of Knowledge loads one snippet on every tab open so you can learn something new in less than 30 secs, opening a different snippet might change the whole concept.

What do you think @petrovicstefanrs should add such feature?

**Comment by petrovicstefanrs** [comment]
@sanderlenaerts You are right, and i will see to it to implement referencing to other snippets. @asantarissy Probably should add this as some snippets can be better understood alongside other snippets. Will put on to do.

Thanks @sanderlenaerts !
