### ISSUE TITLE
Review Ruby Snippets

### ISSUE THREAD

**Issue by petrovicstefanrs** [petrovicstefanrs/30_seconds_of_knowledge#28]
#12 Ruby Snippets

@florianjosefreheis, Hey man, I'm opening this issue to let you and others know that some review of the ruby snippets is needed. 

I'm not a Ruby dev, so I can't do it but if you could find some more ruby devs that could review the snippets, and if anyone else contributing here can help with this, it would be great!

I want to be sure that, what we will be pushing to production soon, is reviewed, properly formatted and written.

**Comment by florianjosefreheis** [comment]
@petrovicstefanrs yeah definitive worth to double check before releasing. Let's see if we can find someone.

**Comment by petrovicstefanrs** [comment]
@florianjosefreheis any luck finding another pair of eyes to double check ruby snippets?

**Comment by florianjosefreheis** [comment]
@petrovicstefanrs, unfortunately, no luck so far, any ideas on how to get the snippets reviewed?

**Comment by petrovicstefanrs** [comment]
@florianjosefreheis, well until we find more ruby people, at least we should go through all the snippets and fix any wording or typing errors. Is it okay if you doublecheck those?

**Comment by renanbona** [comment]
@florianjosefreheis If you allow me, I'll be glad to help with ruby snippets. I've just created two PR for them. If there's anything you want to change about them, tell me.

**Comment by florianjosefreheis** [comment]
@renanbona awesome, I will have a look over the weekend.

**Comment by meg-gutshall** [comment]
Please see my above PR #43. I can probably do a few more throughout the week. I'm about 9 months into programming but it's all been Ruby so I'm very confident with my foundational skills and have the advantage of being able to explain things in a way beginning coders will understand. (I know sometimes experienced devs forget what it's like to know next to nothing!) Hope to be able to help this project out—it's a really cool idea!

**Comment by petrovicstefanrs** [comment]
Closing this as the PR was merged!
