### ISSUE TITLE
Option to save code quickly

### ISSUE THREAD

**Issue by Nisthar** [petrovicstefanrs/30_seconds_of_knowledge#3]
Option to save code quickly for later usage would be nice

**Comment by petrovicstefanrs** [comment]
@Nisthar What do you have in mind? You can copy/paste all code now anyway, in what way would the quick save work? Save as gist? or pdf?
It would be great if you could elaborate

**Comment by asantarissy** [comment]
@petrovicstefanrs I think my PR (#6) covers what @Nisthar is asking for 😃

**Comment by petrovicstefanrs** [comment]
@asantarissy Yep, actually in process of reviewing and merging your PR 😄. Shouldn't be long, maybe a day or two. I want to make sure everything is in sync with what I had in mind. 😄

**Comment by asantarissy** [comment]
AWESOME, just pushed the light theme support 😄

**Comment by petrovicstefanrs** [comment]
> AWESOME, just pushed the light theme support 😄
Nice! I'll get back to you if somethings need a touch up.

**Comment by Nisthar** [comment]
@petrovicstefanrs Yes, I was thinking of something like gist where you can save code snippets and check it later. It would have been nice if there was a plugin to import it to vs code automatically.

**Comment by petrovicstefanrs** [comment]
@Nisthar I've added a library of saved snippets thanks to @asantarissy and it's live now, as for the auto import to vs code, there is a great resource: https://www.npmjs.com/package/30-seconds-of-code
This is the repo I'm scraping the javascript snippets from, and this is their official npm package with all the js snippets you can find on 30 seconds of knowledge. Check them out!
