### ISSUE TITLE
Blacklisting snippets

### ISSUE THREAD

**Issue by lukewhitehouse** [petrovicstefanrs/30_seconds_of_knowledge#32]
Hey, it would be really cool if there was the ability to blacklist snippets you're not interested in. Things that perhaps you already know, etc.

**Comment by petrovicstefanrs** [comment]
@lukewhitehouse Great idea, actually don't know why it never crossed my mind since we already have favorited snippets, this was so obvious. Thank you for the suggestion!

**Comment by Kutomore** [comment]
I'll start working on it, hopefully it should be done soon, probably will make it similar to the save option.
