### ISSUE TITLE
Feature: Toggle saved snippets

### ISSUE THREAD

**Issue by omega-station** [petrovicstefanrs/30_seconds_of_knowledge#37]
How about adding a toggle in the options panel that would hide items that you've already saved--so that you're always seeing fresh content? Thank you (great extension, btw!)

**Comment by petrovicstefanrs** [comment]
Oooooh that's a good idea! Will do that in the next version 😄

**Comment by farskid** [comment]
@petrovicstefanrs I'd like to take this issue. Would you have any idea on how it needs to be done?
