### ISSUE TITLE
Content area is too small in a <600px viewport

### ISSUE THREAD

**Issue by glorywiguno** [petrovicstefanrs/30_seconds_of_knowledge#38]
The content area is squished in a <600px viewport.
Is there any particular reason setting the width for `sok-NewTab-contentContainer` using `100vw - 480px`?
Instead of that we can try using percentage width and paddings around `sok-NewTab-contentContainer`.

**Comment by petrovicstefanrs** [comment]
Fixed, will be released in next version.
