### ISSUE TITLE
Get same example when you click back in browser history

### ISSUE THREAD

**Issue by terzom** [petrovicstefanrs/30_seconds_of_knowledge#45]
It has happened several times that I've open a new tab and just written an address and hit Enter. And sometimes I get a look at the headline of the example and it has been interesting. However, if I want to go back to see it more clearly I can't since it always refreshes the examples.

So a neat feature would be that it would remember what question it was.
Or to be able to see a history of the latest x examples somewhere.

**Comment by petrovicstefanrs** [comment]
@terzom Why not use the save snippet feature that is already there?

**Comment by terzom** [comment]
@petrovicstefanrs because this happens before I can do it. I don't usually open tabs to read but to go x page so this is a matter of seconds. So if I saw something during the time the page load I can't get back or have time to save it. And sometimes I just want to re-read it and not save everything I see.

**Comment by petrovicstefanrs** [comment]
@terzom Ohhh, that's what you meant! Welp hhahha, guess I could do it. Could you just propose the format for this? How many snippets back in time should I save, how would you possibly like that feature to look like and stuff like that?

**Comment by terzom** [comment]
@petrovicstefanrs I would be satisfied if I just could press 'back' and get the same question. Not necessary to show any history, was just an idea if anyone else wanted that features. 

That could have been in a smaller text at the bottom and in settings you could enable to show it or now.

**Comment by petrovicstefanrs** [comment]
@terzom The back in history sounds okay to me. Didn't do any history manipulation with extensions so far so I will need to research it a bit, if it proves to be possible(I assume it will be) I'll implement it.

**Comment by anubhavsrivastava** [comment]
or section which shows last 10/20 snippets shown to me would also help.

**Comment by adejonghm** [comment]
I don't know if it's possible but you could use the time. I mean, if I press "back" before one minute, for example. It could be possible to see the last snippet.

**Comment by thamara** [comment]
One option is to create a new tab (i.e. "Last Seen Snippets) on the "Saved Snippets" as @anubhavsrivastava  has suggested previously. If you are interested in such feature, I would be happy to contribute :)
