### ISSUE TITLE
Snippet error

### ISSUE THREAD

**Issue by coffeecore** [petrovicstefanrs/30_seconds_of_knowledge#47]
Hello.

I think this snippet is wrong : 
https://github.com/petrovicstefanrs/30_seconds_of_knowledge/blob/master/src/assets/snippets/php/isContains.md

```php
function isContains($string, $needle)
{
    return strpos($string, $needle);
}
```

`strpos` function can return `int` or `false`. If you do :
```php
if (isContains('abcd', 'abc')){
}
```
Condition is `false` because `(bool) 0 === false`.

**Comment by petrovicstefanrs** [comment]
@coffeecore  Yep, nice catch! What do you think if I just fix it to this:
```php
function isContains($string, $needle)
{
    return strpos($string, $needle) != -1;
}
```

**Comment by coffeecore** [comment]
I think better way :

```php
function isContains($string, $needle)
{
    return false !== strpos($string, $needle;
}
```
