### ISSUE TITLE
Feature: Screen Saver Mode

### ISSUE THREAD

**Issue by Kutomore** [petrovicstefanrs/30_seconds_of_knowledge#50]
I had an idea, maybe there should be an option on the configs, where you setup a time in seconds and every x seconds the tip on the page would be replaced by a new one. Like an ever changing and never ending stream of tips. By default it should be deactivated maybe, and if you want then you can turn it on. Anyway, just a suggestion, if you think it's a good idea I can implement it.

**Comment by petrovicstefanrs** [comment]
@Kutomore something like a screensaver mode. Hmmm, let me think about it a bit and get back to you, sounds interesting though.

**Comment by Kutomore** [comment]
Exactly, like a screensaver mode, if you think it'd be a good addition I could start working on it.

**Comment by anubhavsrivastava** [comment]
+1 for the idea. I could use it on giant screen that my team has for monitoring,  that I stare every now and then

**Comment by petrovicstefanrs** [comment]
#59 @Kutomore Started working on this
