### ISSUE TITLE
Cannot save React fileDrop tip

### ISSUE THREAD

**Issue by lferrario92** [petrovicstefanrs/30_seconds_of_knowledge#51]
Each time this tip shows up the save button its locked.

The one is React FileDrop tip.

**Comment by petrovicstefanrs** [comment]
@lferrario92 The lock should only be enabled if the snippet is already saved. I know it's a silly question but did you check if its already saved? 😄

**Comment by lferrario92** [comment]
Yeah I had saved it in another window and didn't realize until it showed again, my bad.
