### ISSUE TITLE
Typo in Collapse (React) snippet

### ISSUE THREAD

**Issue by jcmnunes** [petrovicstefanrs/30_seconds_of_knowledge#53]
In the description of the Collapse snippet (React), we can read "Use the React.setState() hook" when it should be "Use the React.useState() hook"

<img width="1402" alt="Screen Shot 2019-04-03 at 13 28 22" src="https://user-images.githubusercontent.com/13286745/55478892-b8b95880-5614-11e9-84cc-a836a69da7e0.png">

**Comment by petrovicstefanrs** [comment]
Indeed right you are. Thank you for the tip, will change it :D
