### ISSUE TITLE
Saved snippet into Chrome Account

### ISSUE THREAD

**Issue by adejonghm** [petrovicstefanrs/30_seconds_of_knowledge#64]
It would be a good idea to save the "**Saved Snippets**" in the **Chrome Account** settings to have the same fragments on any computer that uses the same Chrome Account. I write this because I have a PC in my work but sometimes I work at home with my laptop and I don't have the same snippets on both computers.

This is a great extension. Thanks!!!

**Comment by petrovicstefanrs** [comment]
@adejonghm, not sure this is possible, I will look into saving the extension settings to your google acc, but not sure it will be possible.
