### ISSUE TITLE
Please make safari extension 

### ISSUE THREAD

**Issue by MacFlurry** [petrovicstefanrs/30_seconds_of_knowledge#8]
Hello,

Could you please make a safari extension?

Thanks

**Comment by petrovicstefanrs** [comment]
@MacFlurry Hey, both Safari and Firefox versions are something I plan to start developing as soon as the initial stable version of the main Chrome extension is done.

**Comment by MacFlurry** [comment]
Can't wait. I don't use chrome ☺️

**Comment by petrovicstefanrs** [comment]
Merged this issue with #2. Just to keep it clean.
