### ISSUE TITLE
Firefox add-on missing

### ISSUE THREAD

**Issue by ShirazSuleman** [petrovicstefanrs/30_seconds_of_knowledge#83]
Hi,

When I browse to the [Firefox add-on page](https://addons.mozilla.org/en-US/firefox/addon/30-seconds-of-knowledge/), it says "Oops! We can’t find that page". Is it no longer supported on Firefox?

Thanks
Shiraz

**Comment by petrovicstefanrs** [comment]
@ShirazSuleman Yeah It should be just a temporary problem. I plan to host a new version as soon as it's ready (most likely next week). Sorry for the inconvenience.
