### ISSUE TITLE
Firefox addon doesn't work

### ISSUE THREAD

**Issue by raulhsj** [petrovicstefanrs/30_seconds_of_knowledge#85]
This is the url: https://addons.mozilla.org/en-US/firefox/addon/30-seconds-of-knowledge/
It says that the page couldn't be found

**Comment by petrovicstefanrs** [comment]
Hey @raulhsj, sorry about that. I'm aware it's unavailable at the moment. I had some problems with them reviewing the extension (they couldn't build it). I'm working on that. I hope to have it up again real soon.

**Comment by mmans0ur** [comment]
Hi @petrovicstefanrs
Is there a way to install the addon manually for Firefox?

**Comment by atesztoth** [comment]
> Hi @petrovicstefanrs
> Is there a way to install the addon manually for Firefox?

Hello!
Yes, there is!
Clone the repository, in a terminal enter the folder, run "npm run build:gecko". Then you type "about:config", search for "xpinstall.signatures.required". Set the boolean value to false, and close this page.
After this go to the addons page, and add the extension from file. You'll see a zip file called "gecko_build.zip" in the folder where you cloned the repo to. Add that zip, and you're done!

**Comment by phoffmeister** [comment]
Hey @petrovicstefanrs any news on getting it back to the official addons page for ff?

**Comment by mijailr** [comment]
Still getting this error on firefox

**Comment by mmans0ur** [comment]
> > Hi @petrovicstefanrs
> > Is there a way to install the addon manually for Firefox?
> 
> Hello!
> Yes, there is!
> Clone the repository, in a terminal enter the folder, run "npm run build:gecko".
> Type "about:config" (in Firefox ofc), and search for "xpinstall.signatures.required". Set the boolean value to false, and close this page.
> After this go to the addons page, and add the extension from file. You'll see a zip file called "gecko_build.zip" in the folder where you cloned the repo to. Add that zip, and you're done!

Thanks for the tip
I do as you said except firefox after version 48 does not respect `xpinstall.signatures.required` I switched to firefox developer edition and it's working like a charm.
I found some tricks for firefox normal edition but firefox developer edition sounds good to me.

**Comment by mijailr** [comment]
I was trying to upload a compiled version to get a valid signature. And the failure was related with this part:

https://github.com/petrovicstefanrs/30_seconds_of_knowledge/blob/master/webpack.config.js#L19-L26

After you change the `strict_min_version` to the latest ESR then the automatic test on the addons page pass the first step.

```diff
       gecko: {
		browser_specific_settings: {
			gecko: {
				id: '30secondsofknowledge@petrovicstefan.rs',
-				strict_min_version: '42.0',
+				strict_min_version: '68.0',
			},
		},
	},
```

But then it complains about the uses of `eval` and `innerHTML` functions used by React, so I believe this isn't easy to solve, or anyone know how to use React DOM with safer methods?

**Comment by Akrabut** [comment]
Hi!

I was wondering if there are any news on making this work from the addons page.

**Comment by MarcinOrlowski** [comment]
As addition to comment by @atesztoth - simply rename `gecko_build.zip` to `gecko_build.xpi` and drag & drop that file on Firefox to install.

**Comment by Kreeg** [comment]
Firefox still throws an error. I don't want developer edition of Firefox.
Any updates?

**Comment by lagerfeuer** [comment]
@petrovicstefanrs any news on the Firefox addon? anything we can help with?

**Comment by petrovicstefanrs** [comment]
Small update here. I tried fixing the extension so it worked with FF, but ran into a bunch of other issues. So I decided to do an overhaul. I'll be updating all packages, rewriting react classes to functional components with hooks, and updating manifest to v3. Hopefully, after that is done and the version is stable and easy to develop on, I'll be able to release it as v2 that works on both Chrome and FF. As someone mentioned above, ff complains about using eval and innerHTML, hopefully, this rewrite will address those issues and more. 
So far I have it set up to work with updated webpack and react and manifest versions, but almost nothing else works because of it, so I'm working on that now.

**Comment by petrovicstefanrs** [comment]
Another small update. I managed to make the extension work with the new Webpack and new Manifest versions. In the meantime, I also tried reuploading the current (v1.2) version to Firefox for review, in hopes of releasing it again but it's been around 10 days, and no word back from them. The addon portal also has a notification that says they are experiencing high demand and reviews usually take a few weeks. 

Anyway, now that the dev version of the extension is working I can start rewriting it to functional components with hooks + make some other improvements and simplify some code.

**Comment by petrovicstefanrs** [comment]
Another update. The whole extension is now rewritten to react with hooks and manifest v3. I managed to successfully test the extension on Chrome, Brave and Opera browsers. 

Firefox is still having some issues but hopefully, I'll manage to fix it soon or at least come up with a hack to support it until they officially support manifest v3 (I'll probably use v2 for FF until then). For whatever reason documentation around manifest v3 support for FF was not very clear and there was not much of it but 1 thing I've seen was that they projected they would start support for v3 in 2021 Q4. I'm assuming that will be postponed for Q1 2022 so I'll try to have v2 for FF only until then.

**Comment by tomal02** [comment]
> 

I'd be happy to help get this back up onto Firefox, got it running locally for now.
