### ISSUE TITLE
Add a timer for next time to show a tip

### ISSUE THREAD

**Issue by larzuk91** [petrovicstefanrs/30_seconds_of_knowledge#9]
As a developer, you usually open many tabs in a short period of time, so you can't always read all the tips. Actually, I did try but sometimes I ended forgetting what I was about to do. So, it would be awesome if I can set a timer for when I want the next tip to appear

Cheers!

**Comment by petrovicstefanrs** [comment]
Hey man, thanks for the proposal but actually that problem sounds very specific. I suppose its not something most people would struggle with and not sure on how the timer would be incorporated into the extension from the usability side. Not sure it would be a wise UX move to add such a specific feature this early into the life of a project.

I'm sorry, but I will have to close this issue for now and maybe get back to it once the extension is on stable legs and has proven itself as an MVP.

**Comment by larzuk91** [comment]
Oh, no problem, actually, this is more like feedback than a feature proposal (although it's a feature proposal :p). Nice work btw

**Comment by petrovicstefanrs** [comment]
Hahha actually the problem you described I would call an accidental feature. It just means that the UX is doing its job keeping your focus and interest for the extension alive :P :D

Anyway, as I said maybe in the future, I'll add it but currently I don't see it as an option. 
And thank you!
